global using Application.Models;
global using Domain.Entities;
global using Domain.Interfaces;
global using Infrastructure;
global using Infrastructure.Interfaces;
global using Infrastructure.Repos;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;